version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: db-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:15
    container_name: db-postgres
    environment:
      POSTGRES_DB: testdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - 8080:8080

#  sqlite:
#    image: nouchka/sqlite3:latest
#    container_name: db-sqlite
#    volumes:
#      - ./data/sqlite:/root/db
#    command: tail -f /dev/null # keep the container running for inspection

volumes:
  mysql_data:
  postgres_data:
